CREATE DATABASE IF NOT EXISTS storage_db  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS fl_database DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
