version: '3.3'

networks:
  platappnet:
    ipam:
      driver: default

services:
  # 平台
  postgres_platform:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ppcp
      POSTGRES_USER: root
    networks:
      - platappnet

  platform:
    image: "101.251.207.188:5000/ppcp:hczy"
    environment:
      - DB_URI=postgres://root:123456@postgres_platform:5432/ppcp
      - ZK_HOST=zookeeper
      - ZK_PORT=2181
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=123456
      - PLATFORM_SECRET=thisisplatform
    ports:
      - 5555:8000
    networks:
      - platappnet
    depends_on:
      - postgres_platform

  platform_page:
    image: "101.251.207.188:5000/ppcp-frontend:hczy"
    environment:
      - VUE_APP_BASE_API=${IP}:5555
    ports:
      - 8080:80
    env_file:
      - .env
