version: '3.3'

networks:
  appnet:
    ipam:
      driver: default

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./fl-scheduler/mysql/data:/var/lib/mysql
      - ./fl-scheduler/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4
    environment:
      MYSQL_ROOT_PASSWORD: qifenbao602
    networks:
      - appnet
      
  minio:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ppcn
      POSTGRES_USER: root
    networks:
      - appnet

  fl-scheduler:
    image: "${RegistryURI}/fl-scheduler:${TAG}"
    ports:
      - 8000:8000
    environment:
      - CONSTANT_SETTINGS_FILE=/opt/FL-Scheduler/config/constant_settings.yaml
    volumes:
      - ./fl-scheduler/config:/opt/FL-Scheduler/config
    networks:
      - appnet

  ppcn:
    image: "${RegistryURI}/ppcn:hczy"
    ports:
      - 10000:10000
    environment:
      - MINIO_SK=minioadmin
      - DIAGRAM_RENDER_URL=http://diagram_render:8000
      - ADDR=http://ppcn:10000
      - DB_URI=postgres://root:123456@postgres:5432/ppcn
      - IP=192.168.50.26
      - LOCAL_HOST=192.168.50.26
      - LOCAL_IP=192.168.50.26
      - PLATFORM_SECRET=part1
      - LOCAL_PORT=10000
      - CLIENT_ENDPOINT=http://192.168.50.26:8000
      - MINIO_ENDPOINT=192.168.50.26:9000
      - MINIO_AK=minioadmin
      - DB_SCHEDULER_URI=mysql://root:qifenbao602@mysql:3306/fl_database
    depends_on:
      - postgres
      - minio
      - fl-scheduler
    networks:
      - appnet

  diagram_render:
    image: 101.251.207.188:5000/plot:1.1

  front_end:
    image: "${RegistryURI}/ppcn-frontend:hczy"
    environment:
      - VUE_APP_BASE_API=${NODE_RESTFUL_API}
    ports:
      - 8081:80
    networks:
      - appnet
